services:
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: administrador@example.com
      PGADMIN_DEFAULT_PASSWORD: password123
    ports:
      - "80:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  redis:
    image: redis:7.2
    container_name: redis_server
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass my_redis_password
    volumes:
      - redis_data:/data
  redisinsight:
    image: redislabs/redisinsight:1.14.0  # Versión estable 1.x
    container_name: redis_insight
    restart: unless-stopped
    ports:
      - "8001:8001"
  redis_commander:
    image: rediscommander/redis-commander:latest
    container_name: redis_commander
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379:0:my_redis_password
    ports:
      - "8081:8081"
    depends_on:
      - redis

volumes:
  pgadmin_data:
  redis_data: